get:
  summary: get a single job's most recent deployment
  operationId: getJobLatestDeployment
  tags:
    - jobs
  parameters:
    - $ref: '../../parameters/query/namespace.yaml'
    - $ref: '../../parameters/query/region.yaml'
    - $ref: '../../parameters/query/index.yaml'
    - $ref: '../../parameters/query/wait.yaml'

    - $ref: '../../parameters/path/job_id.yaml'
  responses:
    '200':
      description: job deployment response
      content:
        application/json:
          schema:
            $ref: '../../schemas/Deployment.yaml'
